#!/usr/bin/env python3
"""Build all eleven installable scripts from one runtime and eleven skins.

No bundler or network is required. --check verifies the checked-in distributables.
The root widget.js intentionally remains an exact alias of widget/widget.js.
"""
import argparse
import base64
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
WIDGET = ROOT / "widget"


def font_css():
    # OFL-licensed Vazirmatn 5.3.0, supplied by @fontsource-variable/vazirmatn.
    # Inline data avoids a third-party CDN, tracking, FOUT from a blocked CDN,
    # or a separate customer asset deployment. The font name is widget-specific.
    ranges = {
        "arabic": "U+0600-06FF,U+0750-077F,U+0870-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FEFC,U+102E0-102FB,U+10E60-10EFF,U+1EE00-1EEFF",
        "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    }
    css = []
    for subset, unicode_range in ranges.items():
        data = base64.b64encode((WIDGET / "fonts" / f"vazirmatn-{subset}.woff2").read_bytes()).decode()
        css.append("@font-face{font-family:'ASW Vazirmatn';font-style:normal;font-weight:100 900;font-display:swap;"
                   f"src:url(data:font/woff2;base64,{data}) format('woff2');unicode-range:{unicode_range}" + "}")
    return "\n".join(css)


def replace_once(text, marker, replacement):
    if text.count(marker) != 1:
        raise ValueError(f"Expected exactly one {marker!r}")
    return text.replace(marker, replacement)


def generate():
    runtime = (ROOT / "scripts" / "widget-runtime.js").read_text(encoding="utf-8")
    core = (WIDGET / "design-core.css").read_text(encoding="utf-8")
    manifest = json.loads((WIDGET / "themes" / "manifest.json").read_text(encoding="utf-8"))
    if len(manifest) != 11:
        raise ValueError("All eleven themes must be built")
    for name, theme in manifest.items():
        design = core + "\n" + (WIDGET / "themes" / f"{name}.css").read_text(encoding="utf-8")
        if "`" in design or "${" in design:
            raise ValueError(f"Unsafe JavaScript template literal in {name} CSS")
        result = runtime
        result = replace_once(result, "__ASW_THEME_LABEL__", theme["label"])
        result = replace_once(result, "/* @asw-theme */ null", json.dumps({"name": name, **theme}, ensure_ascii=False))
        for marker, filename in (("live-handoff", "live-handoff.js"), ("ui-shell", "ui-shell.js")):
            result = replace_once(result, f"/* @asw-{marker} */", (WIDGET / filename).read_text(encoding="utf-8").rstrip())
        result = replace_once(result, "/* @asw-design */", design.rstrip())
        result = replace_once(result, '/* @asw-font-css */ ""', json.dumps(font_css(), ensure_ascii=False))
        license_text = (WIDGET / "fonts" / "OFL.txt").read_text(encoding="utf-8").strip()
        if "*/" in license_text:
            raise ValueError("Unsafe font-license comment")
        result = "// GENERATED by scripts/build_widgets.py. Edit the shared sources, not this file.\n" + "/* Embedded Vazirmatn font license:\n" + license_text + "\n*/\n" + result.rstrip() + "\n"
        filename = "widget.js" if name == "classic" else f"widget-{name}.js"
        yield WIDGET / filename, result
        if name == "classic":
            yield ROOT / "widget.js", result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generate():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"Built {path.relative_to(ROOT)}")
    if stale:
        print("Stale bundles: " + ", ".join(stale) + ". Run npm run build.", file=sys.stderr)
        return 1
    if args.check:
        print("All 11 bundles and the root alias are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
